// mail-react/src/features/admin/ApiKeyTester.tsx
import { useEffect, useMemo, useState } from "react";
import {
  Eye,
  EyeOff,
  FlaskConical,
  Inbox,
  KeyRound,
  Send,
  ShieldCheck,
} from "lucide-react";
import { Button, ConfirmDialog, Input } from "@/components/ui";
import { publicApiRequest } from "./apiControlApi";
import type {
  PublicApiResult,
  PublicMailbox,
  PublicMessage,
} from "./apiControlTypes";

interface MailboxResponse {
  items: PublicMailbox[];
  nextCursor: string | null;
}

interface DomainResponse {
  items: string[];
}

interface MessageResponse {
  items: PublicMessage[];
  total: number;
  nextCursor: number | null;
}

export interface ApiKeyTesterProps {
  initialKey?: string;
}

export function ApiKeyTester({ initialKey = "" }: ApiKeyTesterProps) {
  const [apiKey, setApiKey] = useState(initialKey);
  const [showKey, setShowKey] = useState(false);
  const [loading, setLoading] = useState("");
  const [result, setResult] = useState<PublicApiResult>();
  const [mailboxes, setMailboxes] = useState<PublicMailbox[]>([]);
  const [domains, setDomains] = useState<string[]>([]);
  const [direction, setDirection] = useState<"received" | "sent">("received");
  const [mailboxId, setMailboxId] = useState("");
  const [cursor, setCursor] = useState("");
  const [limit, setLimit] = useState("20");
  const [messageId, setMessageId] = useState("");
  const [senderMode, setSenderMode] = useState<"dynamic" | "mailbox">(
    "dynamic",
  );
  const [senderMailboxId, setSenderMailboxId] = useState("");
  const [localPart, setLocalPart] = useState("notice");
  const [domain, setDomain] = useState("");
  const [to, setTo] = useState("");
  const [subject, setSubject] = useState("HPC Mail API 测试");
  const [text, setText] = useState(
    "这是一封由本地浏览器 API 测试器发送的邮件。",
  );
  const [sendOpen, setSendOpen] = useState(false);

  useEffect(() => {
    if (initialKey) setApiKey(initialKey);
  }, [initialKey]);

  const disabled = !apiKey.trim() || Boolean(loading);
  const recipients = useMemo(
    () => [
      ...new Set(
        to
          .split(/[,，;；\s]+/)
          .map((item) => item.trim())
          .filter(Boolean),
      ),
    ],
    [to],
  );

  async function run<T>(
    name: string,
    task: () => Promise<PublicApiResult<T>>,
  ): Promise<PublicApiResult<T> | undefined> {
    if (!apiKey.trim() || loading) return undefined;
    setLoading(name);
    try {
      const response = await task();
      setResult(response);
      return response;
    } finally {
      setLoading("");
    }
  }

  async function testStatus() {
    await run("status", () => publicApiRequest(apiKey, "/status"));
  }

  async function loadMailboxes() {
    const response = await run<MailboxResponse>("mailboxes", () =>
      publicApiRequest(apiKey, "/mailboxes?limit=30"),
    );
    if (response?.ok && response.data) {
      setMailboxes(response.data.items);
      if (!senderMailboxId && response.data.items[0])
        setSenderMailboxId(String(response.data.items[0].id));
    }
  }

  async function loadDomains() {
    const response = await run<DomainResponse>("domains", () =>
      publicApiRequest(apiKey, "/domains"),
    );
    if (response?.ok && response.data) {
      setDomains(response.data.items);
      if (!domain && response.data.items[0]) setDomain(response.data.items[0]);
    }
  }

  async function listMessages() {
    const query = new URLSearchParams({ direction, limit: limit || "20" });
    if (cursor) query.set("cursor", cursor);
    if (direction === "received" && mailboxId)
      query.set("mailboxId", mailboxId);
    await run<MessageResponse>("messages", () =>
      publicApiRequest(apiKey, `/messages?${query}`),
    );
  }

  async function getMessage() {
    if (!/^\d+$/.test(messageId) || Number(messageId) < 1) return;
    await run<PublicMessage>("detail", () =>
      publicApiRequest(apiKey, `/messages/${messageId}`),
    );
  }

  async function sendMessage() {
    if (!recipients.length || !subject.trim() || !text.trim()) return;
    const from =
      senderMode === "mailbox"
        ? { mailboxId: Number(senderMailboxId) }
        : { localPart: localPart.trim(), domain };
    setSendOpen(false);
    await run<PublicMessage>("send", () =>
      publicApiRequest(apiKey, "/messages", {
        method: "POST",
        body: { from, to: recipients, subject: subject.trim(), text },
      }),
    );
  }

  return (
    <div className="space-y-5" role="tabpanel" aria-label="API 密钥测试器">
      <header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h2 className="text-base font-semibold text-slate-950">
            浏览器本地密钥测试
          </h2>
          <p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">
            请求只会从当前浏览器发往当前站点的 <code>/api/v1</code>
            ，不会携带登录 Cookie。
          </p>
        </div>
        <span className="inline-flex min-h-8 w-fit items-center gap-1.5 rounded-full bg-emerald-50 px-3 text-xs font-semibold text-emerald-800">
          <ShieldCheck className="size-4" />
          密钥仅保存在组件内存
        </span>
      </header>

      <section
        className="rounded-2xl border border-slate-200 bg-white p-4"
        aria-labelledby="tester-key-heading"
      >
        <label
          id="tester-key-heading"
          htmlFor="api-tester-key"
          className="text-sm font-medium text-slate-700"
        >
          API 密钥
        </label>
        <div className="mt-2 grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto_auto]">
          <Input
            id="api-tester-key"
            type={showKey ? "text" : "password"}
            value={apiKey}
            autoComplete="off"
            spellCheck={false}
            placeholder="hpc_live_…"
            onChange={(event) => setApiKey(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Enter") void testStatus();
            }}
          />
          <Button
            variant="secondary"
            aria-pressed={showKey}
            onClick={() => setShowKey((value) => !value)}
          >
            {showKey ? (
              <EyeOff className="size-4" />
            ) : (
              <Eye className="size-4" />
            )}
            {showKey ? "隐藏" : "显示"}
          </Button>
          <Button
            loading={loading === "status"}
            disabled={!apiKey.trim()}
            onClick={() => void testStatus()}
          >
            <FlaskConical className="size-4" />
            测试连接
          </Button>
        </div>
      </section>

      <div className="grid gap-4 lg:grid-cols-2">
        <section
          className="rounded-2xl border border-slate-200 bg-white p-4"
          aria-labelledby="resources-heading"
        >
          <div className="flex items-start gap-3">
            <KeyRound className="mt-0.5 size-5 text-blue-600" />
            <div>
              <h3
                id="resources-heading"
                className="font-semibold text-slate-900"
              >
                邮箱与域名
              </h3>
              <p className="mt-1 text-xs leading-5 text-slate-500">
                验证 mailbox.read 和 mail.send 权限，并加载后续测试选项。
              </p>
            </div>
          </div>
          <div className="mt-4 grid grid-cols-2 gap-2">
            <Button
              variant="secondary"
              loading={loading === "mailboxes"}
              disabled={disabled}
              onClick={() => void loadMailboxes()}
            >
              查看邮箱
            </Button>
            <Button
              variant="secondary"
              loading={loading === "domains"}
              disabled={disabled}
              onClick={() => void loadDomains()}
            >
              查看域名
            </Button>
          </div>
          <p className="mt-3 text-xs text-slate-500">
            已加载 {mailboxes.length} 个邮箱、{domains.length} 个授权域名。
          </p>
        </section>

        <section
          className="rounded-2xl border border-slate-200 bg-white p-4"
          aria-labelledby="messages-heading"
        >
          <div className="flex items-start gap-3">
            <Inbox className="mt-0.5 size-5 text-blue-600" />
            <div>
              <h3
                id="messages-heading"
                className="font-semibold text-slate-900"
              >
                邮件列表与筛选
              </h3>
              <p className="mt-1 text-xs leading-5 text-slate-500">
                读取收件或发件记录，收件记录支持邮箱筛选。
              </p>
            </div>
          </div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2">
            <label className="grid gap-1 text-xs font-medium text-slate-600">
              方向
              <select
                className="h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm"
                value={direction}
                onChange={(event) =>
                  setDirection(event.target.value as "received" | "sent")
                }
              >
                <option value="received">收件</option>
                <option value="sent">发件</option>
              </select>
            </label>
            <label className="grid gap-1 text-xs font-medium text-slate-600">
              邮箱筛选
              <select
                className="h-11 min-w-0 rounded-xl border border-slate-300 bg-white px-3 text-sm disabled:bg-slate-100"
                value={mailboxId}
                disabled={direction === "sent"}
                onChange={(event) => setMailboxId(event.target.value)}
              >
                <option value="">全部邮箱</option>
                {mailboxes.map((mailbox) => (
                  <option key={mailbox.id} value={mailbox.id}>
                    {mailbox.address}
                  </option>
                ))}
              </select>
            </label>
            <label className="grid gap-1 text-xs font-medium text-slate-600">
              游标（可选）
              <Input
                value={cursor}
                inputMode="numeric"
                onChange={(event) => setCursor(event.target.value)}
              />
            </label>
            <label className="grid gap-1 text-xs font-medium text-slate-600">
              数量（1–50）
              <Input
                value={limit}
                inputMode="numeric"
                onChange={(event) => setLimit(event.target.value)}
              />
            </label>
          </div>
          <Button
            className="mt-4 w-full"
            loading={loading === "messages"}
            disabled={disabled}
            onClick={() => void listMessages()}
          >
            查看邮件
          </Button>
        </section>

        <section
          className="rounded-2xl border border-slate-200 bg-white p-4"
          aria-labelledby="detail-heading"
        >
          <h3 id="detail-heading" className="font-semibold text-slate-900">
            邮件详情
          </h3>
          <p className="mt-1 text-xs leading-5 text-slate-500">
            按消息 ID 验证详情和附件元数据。
          </p>
          <label className="mt-4 grid gap-1 text-xs font-medium text-slate-600">
            消息 ID
            <Input
              value={messageId}
              inputMode="numeric"
              placeholder="例如 123"
              onChange={(event) => setMessageId(event.target.value)}
            />
          </label>
          <Button
            className="mt-3 w-full"
            variant="secondary"
            loading={loading === "detail"}
            disabled={disabled || !/^\d+$/.test(messageId)}
            onClick={() => void getMessage()}
          >
            查看详情
          </Button>
        </section>

        <section
          className="rounded-2xl border border-slate-200 bg-white p-4"
          aria-labelledby="send-test-heading"
        >
          <div className="flex items-start gap-3">
            <Send className="mt-0.5 size-5 text-blue-600" />
            <div>
              <h3
                id="send-test-heading"
                className="font-semibold text-slate-900"
              >
                发送真实测试邮件
              </h3>
              <p className="mt-1 text-xs leading-5 text-slate-500">
                提交前会再次显示发件人与收件人并要求确认。
              </p>
            </div>
          </div>
          <div className="mt-4 space-y-3">
            <fieldset>
              <legend className="text-xs font-medium text-slate-600">
                发件方式
              </legend>
              <div className="mt-1 grid grid-cols-2 gap-2">
                <Button
                  variant={senderMode === "dynamic" ? "primary" : "secondary"}
                  aria-pressed={senderMode === "dynamic"}
                  onClick={() => setSenderMode("dynamic")}
                >
                  任意前缀
                </Button>
                <Button
                  variant={senderMode === "mailbox" ? "primary" : "secondary"}
                  aria-pressed={senderMode === "mailbox"}
                  onClick={() => setSenderMode("mailbox")}
                >
                  注册邮箱
                </Button>
              </div>
            </fieldset>
            {senderMode === "dynamic" ? (
              <div className="grid gap-2 sm:grid-cols-2">
                <label className="grid gap-1 text-xs font-medium text-slate-600">
                  邮箱前缀
                  <Input
                    value={localPart}
                    onChange={(event) => setLocalPart(event.target.value)}
                  />
                </label>
                <label className="grid gap-1 text-xs font-medium text-slate-600">
                  授权域名
                  <select
                    className="h-11 min-w-0 rounded-xl border border-slate-300 bg-white px-3 text-sm"
                    value={domain}
                    onChange={(event) => setDomain(event.target.value)}
                  >
                    <option value="">选择域名</option>
                    {domains.map((item) => (
                      <option key={item} value={item}>
                        @{item}
                      </option>
                    ))}
                  </select>
                </label>
              </div>
            ) : (
              <label className="grid gap-1 text-xs font-medium text-slate-600">
                注册邮箱
                <select
                  className="h-11 min-w-0 rounded-xl border border-slate-300 bg-white px-3 text-sm"
                  value={senderMailboxId}
                  onChange={(event) => setSenderMailboxId(event.target.value)}
                >
                  <option value="">选择邮箱</option>
                  {mailboxes.map((mailbox) => (
                    <option key={mailbox.id} value={mailbox.id}>
                      {mailbox.address}
                    </option>
                  ))}
                </select>
              </label>
            )}
            <label className="grid gap-1 text-xs font-medium text-slate-600">
              收件人
              <Input
                value={to}
                placeholder="name@example.com"
                onChange={(event) => setTo(event.target.value)}
              />
            </label>
            <label className="grid gap-1 text-xs font-medium text-slate-600">
              主题
              <Input
                value={subject}
                maxLength={998}
                onChange={(event) => setSubject(event.target.value)}
              />
            </label>
            <label className="grid gap-1 text-xs font-medium text-slate-600">
              正文
              <textarea
                className="min-h-24 rounded-xl border border-slate-300 px-3 py-2 text-sm leading-6 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20"
                value={text}
                onChange={(event) => setText(event.target.value)}
              />
            </label>
            <Button
              className="w-full"
              loading={loading === "send"}
              disabled={
                disabled ||
                !recipients.length ||
                !subject.trim() ||
                !text.trim() ||
                (senderMode === "dynamic"
                  ? !localPart.trim() || !domain
                  : !senderMailboxId)
              }
              onClick={() => setSendOpen(true)}
            >
              发送测试邮件
            </Button>
          </div>
        </section>
      </div>

      {result && (
        <section
          className="overflow-hidden rounded-2xl border border-slate-200 bg-white"
          aria-live="polite"
          aria-labelledby="api-result-heading"
        >
          <header className="grid gap-3 border-b border-slate-200 bg-slate-50 px-4 py-3 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center">
            <div className="flex min-w-0 flex-wrap items-center gap-2">
              <span
                className={`rounded-lg px-2 py-1 text-xs font-bold ${result.ok ? "bg-emerald-100 text-emerald-800" : "bg-red-100 text-red-800"}`}
              >
                HTTP {result.status}
              </span>
              <h3
                id="api-result-heading"
                className="min-w-0 break-all text-sm font-semibold text-slate-800"
              >
                {result.method} {result.path}
              </h3>
            </div>
            <dl className="grid grid-cols-2 gap-x-5 gap-y-2 text-xs sm:grid-cols-4">
              <div>
                <dt className="text-slate-500">耗时</dt>
                <dd className="font-medium text-slate-800">
                  {result.durationMs} ms
                </dd>
              </div>
              <div>
                <dt className="text-slate-500">Request ID</dt>
                <dd
                  className="max-w-32 truncate font-medium text-slate-800"
                  title={result.requestId}
                >
                  {result.requestId || "—"}
                </dd>
              </div>
              <div>
                <dt className="text-slate-500">剩余请求</dt>
                <dd className="font-medium text-slate-800">
                  {result.rateRemaining || "—"}
                  {result.rateLimit ? ` / ${result.rateLimit}` : ""}
                </dd>
              </div>
              <div>
                <dt className="text-slate-500">重置时间</dt>
                <dd className="font-medium text-slate-800">
                  {result.rateReset || "—"}
                </dd>
              </div>
            </dl>
          </header>
          <pre className="m-0 max-h-96 overflow-auto bg-slate-950 p-4 text-xs leading-6 whitespace-pre-wrap break-words text-slate-200">
            <code>{result.body}</code>
          </pre>
        </section>
      )}
      <ConfirmDialog
        open={sendOpen}
        title="发送真实测试邮件？"
        description={`将从 ${senderMode === "mailbox" ? mailboxes.find((mailbox) => String(mailbox.id) === senderMailboxId)?.address || `邮箱 #${senderMailboxId}` : `${localPart}@${domain}`} 向 ${recipients.join(", ")} 发送邮件。`}
        confirmLabel="确认发送"
        loading={loading === "send"}
        onOpenChange={setSendOpen}
        onConfirm={() => void sendMessage()}
      />
    </div>
  );
}

// mail-vue/src/views/api-control/ApiKeyTester.vue
<template>
  <div class="api-tester" role="tabpanel">
    <header class="tester-heading">
      <div>
        <h3>{{ t('apiKeyTesterTitle') }}</h3>
        <p>{{ t('apiKeyTesterDescription') }}</p>
      </div>
      <span class="memory-badge"><ShieldCheck :size="16" />{{ t('apiKeyMemoryOnly') }}</span>
    </header>

    <section class="tester-auth">
      <label for="api-test-key">{{ t('apiKey') }}</label>
      <div class="key-input-row">
        <el-input
          id="api-test-key"
          v-model="apiKey"
          type="password"
          show-password
          autocomplete="off"
          spellcheck="false"
          :placeholder="t('apiKeyTesterPlaceholder')"
          @keyup.enter="testConnection"
        />
        <AppButton :loading="loading === 'status'" :disabled="!apiKey.trim()" @click="testConnection">
          {{ t('testApiKey') }}
        </AppButton>
      </div>
    </section>

    <div class="tester-grid">
      <section class="operation-card">
        <div class="operation-card__heading">
          <Inbox :size="20" />
          <div><h4>{{ t('testInbox') }}</h4><p>{{ t('testInboxDescription') }}</p></div>
        </div>
        <label>
          <span>{{ t('mailboxFilter') }}</span>
          <el-select v-model="mailboxId" :placeholder="t('allMailboxes')">
            <el-option :label="t('allMailboxes')" value="" />
            <el-option v-for="mailbox in mailboxes" :key="mailbox.id" :label="mailbox.address" :value="String(mailbox.id)" />
          </el-select>
        </label>
        <div class="operation-actions">
          <AppButton variant="secondary" :loading="loading === 'resources'" :disabled="!apiKey.trim()" @click="loadResources">
            {{ t('loadApiOptions') }}
          </AppButton>
          <AppButton :loading="loading === 'inbox'" :disabled="!apiKey.trim()" @click="testInbox">
            {{ t('viewInbox') }}
          </AppButton>
        </div>
      </section>

      <section class="operation-card operation-card--send">
        <div class="operation-card__heading">
          <Send :size="20" />
          <div><h4>{{ t('testSendMail') }}</h4><p>{{ t('testSendMailDescription') }}</p></div>
        </div>
        <fieldset class="sender-mode">
          <legend>{{ t('senderType') }}</legend>
          <el-radio-group v-model="sendForm.senderType">
            <el-radio-button value="mailbox">{{ t('registeredMailbox') }}</el-radio-button>
            <el-radio-button value="dynamic">{{ t('dynamicSender') }}</el-radio-button>
          </el-radio-group>
        </fieldset>
        <label v-if="sendForm.senderType === 'mailbox'">
          <span>{{ t('senderMailbox') }}</span>
          <el-select v-model="sendForm.mailboxId" :placeholder="t('selectSenderMailbox')">
            <el-option v-for="mailbox in mailboxes" :key="mailbox.id" :label="mailbox.address" :value="String(mailbox.id)" />
          </el-select>
        </label>
        <div v-else class="dynamic-sender">
          <label><span>{{ t('emailPrefix') }}</span><el-input v-model.trim="sendForm.localPart" placeholder="notice" /></label>
          <label><span>{{ t('emailDomain') }}</span><el-select v-model="sendForm.domain" :placeholder="t('selectDomain')"><el-option v-for="domain in domains" :key="domain" :label="`@${domain}`" :value="domain" /></el-select></label>
        </div>
        <label><span>{{ t('recipientAddresses') }}</span><el-input v-model="sendForm.to" :placeholder="t('recipientAddressesPlaceholder')" /></label>
        <label><span>{{ t('subject') }}</span><el-input v-model="sendForm.subject" maxlength="998" /></label>
        <label><span>{{ t('plainTextBody') }}</span><el-input v-model="sendForm.text" type="textarea" :rows="3" /></label>
        <AppButton :loading="loading === 'send'" :disabled="!canSend" @click="testSend">
          {{ t('sendTestEmail') }}
        </AppButton>
      </section>
    </div>

    <section v-if="result" class="tester-result" aria-live="polite">
      <header>
        <div>
          <span class="http-status" :class="{ 'http-status--error': !result.ok }">HTTP {{ result.status }}</span>
          <strong>{{ result.method }} {{ result.path }}</strong>
        </div>
        <dl>
          <div><dt>{{ t('apiDuration') }}</dt><dd>{{ result.duration }} ms</dd></div>
          <div><dt>{{ t('requestId') }}</dt><dd>{{ result.requestId || '—' }}</dd></div>
          <div><dt>{{ t('rateLimitRemaining') }}</dt><dd>{{ result.rateRemaining || '—' }}</dd></div>
        </dl>
      </header>
      <pre><code>{{ result.body }}</code></pre>
    </section>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, reactive, ref } from 'vue'
import { Inbox, Send, ShieldCheck } from '@lucide/vue'
import { useI18n } from 'vue-i18n'
import AppButton from '@/components/ui/AppButton.vue'

const { t } = useI18n()
const apiKey = ref('')
const loading = ref('')
const mailboxes = ref([])
const domains = ref([])
const mailboxId = ref('')
const result = ref(null)
const sendForm = reactive({
  senderType: 'mailbox',
  mailboxId: '',
  localPart: '',
  domain: '',
  to: '',
  subject: t('apiTestDefaultSubject'),
  text: t('apiTestDefaultBody')
})

const canSend = computed(() => {
  const hasSender = sendForm.senderType === 'mailbox'
    ? Boolean(sendForm.mailboxId)
    : Boolean(sendForm.localPart && sendForm.domain)
  return Boolean(apiKey.value.trim() && hasSender && sendForm.to.trim() && sendForm.subject.trim())
})

defineExpose({
  useKey(secret) {
    apiKey.value = String(secret || '')
  }
})

onBeforeUnmount(clearSensitiveState)

function clearSensitiveState() {
  apiKey.value = ''
  result.value = null
}

async function apiRequest(path, options = {}) {
  const controller = new AbortController()
  const timeout = window.setTimeout(() => controller.abort(), 15000)
  const startedAt = performance.now()
  const method = options.method || 'GET'
  try {
    const response = await window.fetch(`${window.location.origin}/api/v1${path}`, {
      method,
      headers: {
        Authorization: `Bearer ${apiKey.value.trim()}`,
        ...(options.body ? { 'Content-Type': 'application/json' } : {})
      },
      body: options.body ? JSON.stringify(options.body) : undefined,
      credentials: 'omit',
      cache: 'no-store',
      referrerPolicy: 'no-referrer',
      signal: controller.signal
    })
    const text = await response.text()
    let formatted = text
    try { formatted = JSON.stringify(JSON.parse(text), null, 2) } catch (_) { /* keep plain response */ }
    result.value = {
      ok: response.ok,
      status: response.status,
      method,
      path,
      duration: Math.round(performance.now() - startedAt),
      requestId: response.headers.get('X-Request-ID'),
      rateRemaining: response.headers.get('X-RateLimit-Remaining'),
      body: formatted.slice(0, 12000) || '(empty response)'
    }
    if (!response.ok) throw new Error(formatted || `HTTP ${response.status}`)
    return text ? JSON.parse(text) : {}
  } catch (error) {
    if (error?.name === 'AbortError') {
      result.value = { ok: false, status: t('timeout'), method, path, duration: 15000, requestId: '', rateRemaining: '', body: t('apiRequestTimedOut') }
    } else if (!result.value || result.value.path !== path) {
      result.value = { ok: false, status: t('networkError'), method, path, duration: Math.round(performance.now() - startedAt), requestId: '', rateRemaining: '', body: String(error?.message || error) }
    }
    throw error
  } finally {
    window.clearTimeout(timeout)
  }
}

async function run(type, task) {
  if (!apiKey.value.trim()) return
  loading.value = type
  try {
    await task()
  } catch (_) {
    // The structured error response is already visible in the result panel.
  } finally {
    loading.value = ''
  }
}

function testConnection() {
  return run('status', async () => {
    await apiRequest('/status')
    ElMessage.success(t('apiKeyTestSucceeded'))
  })
}

function loadResources() {
  return run('resources', async () => {
    let loaded = 0
    try {
      const mailboxResponse = await apiRequest('/mailboxes?limit=30')
      mailboxes.value = mailboxResponse?.data?.items || []
      if (!sendForm.mailboxId && mailboxes.value.length) sendForm.mailboxId = String(mailboxes.value[0].id)
      loaded += 1
    } catch (_) {
      mailboxes.value = []
    }
    try {
      const domainResponse = await apiRequest('/domains')
      domains.value = domainResponse?.data?.items || []
      if (!sendForm.domain && domains.value.length) sendForm.domain = domains.value[0]
      loaded += 1
    } catch (_) {
      domains.value = []
    }
    if (loaded) ElMessage.success(t('apiOptionsLoaded'))
  })
}

function testInbox() {
  return run('inbox', async () => {
    const query = new URLSearchParams({ direction: 'received', limit: '20' })
    if (mailboxId.value) query.set('mailboxId', mailboxId.value)
    await apiRequest(`/messages?${query}`)
  })
}

async function testSend() {
  const recipients = sendForm.to.split(/[\s,;]+/).map(item => item.trim()).filter(Boolean)
  try {
    await ElMessageBox.confirm(
      t('confirmApiTestSend', { recipients: recipients.join(', ') }),
      t('sendTestEmail'),
      { type: 'warning', confirmButtonText: t('send'), cancelButtonText: t('cancel') }
    )
  } catch (_) {
    return
  }
  return run('send', async () => {
    const from = sendForm.senderType === 'mailbox'
      ? { mailboxId: Number(sendForm.mailboxId) }
      : { localPart: sendForm.localPart, domain: sendForm.domain }
    await apiRequest('/messages', {
      method: 'POST',
      body: { from, to: recipients, subject: sendForm.subject, text: sendForm.text }
    })
    ElMessage.success(t('apiTestMailSent'))
  })
}
</script>

<style scoped>
.api-tester { min-height: 0; padding: clamp(16px, 3vw, 28px); overflow-y: auto; display: grid; align-content: start; gap: 18px; }
.tester-heading { display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; }
.tester-heading h3 { font-size: 1rem; }
.tester-heading p { margin-block-start: 4px; color: var(--muted-foreground); font-size: .8125rem; line-height: 1.5; }
.memory-badge { min-height: 30px; padding-inline: 10px; display: inline-flex; align-items: center; gap: 6px; border-radius: 999px; color: var(--success); background: var(--success-soft); font-size: .75rem; font-weight: 700; white-space: nowrap; }
.tester-auth, .operation-card, .tester-result { border: 1px solid var(--border); border-radius: var(--radius-card); background: var(--surface); }
.tester-auth { padding: 14px; display: grid; gap: 7px; }
.tester-auth label, .operation-card label > span, .sender-mode legend { color: var(--foreground); font-size: .75rem; font-weight: 700; }
.key-input-row { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 8px; }
.tester-grid { display: grid; grid-template-columns: minmax(280px, .8fr) minmax(360px, 1.2fr); align-items: start; gap: 14px; }
.operation-card { padding: 16px; display: grid; gap: 14px; }
.operation-card__heading { display: flex; gap: 10px; color: var(--primary); }
.operation-card__heading h4 { color: var(--foreground); font-size: .9375rem; }
.operation-card__heading p { margin-block-start: 3px; color: var(--muted-foreground); font-size: .75rem; line-height: 1.45; }
.operation-card label, .dynamic-sender label { min-width: 0; display: grid; gap: 6px; }
.operation-card :deep(.el-select) { width: 100%; }
.operation-actions { display: flex; justify-content: flex-end; gap: 8px; }
.sender-mode { padding: 0; border: 0; display: grid; gap: 7px; }
.sender-mode :deep(.el-radio-group) { display: grid; grid-template-columns: 1fr 1fr; }
.sender-mode :deep(.el-radio-button__inner) { width: 100%; }
.dynamic-sender { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
.tester-result { overflow: hidden; }
.tester-result > header { padding: 12px 14px; display: flex; align-items: center; justify-content: space-between; gap: 14px; border-block-end: 1px solid var(--border); background: var(--surface-subtle); }
.tester-result > header > div { display: flex; align-items: center; gap: 9px; }
.tester-result strong { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .75rem; }
.tester-result dl { display: flex; gap: 16px; }
.tester-result dl div { display: grid; gap: 2px; }
.tester-result dt { color: var(--subtle-foreground); font-size: .625rem; text-transform: uppercase; }
.tester-result dd { max-width: 180px; overflow: hidden; font-size: .6875rem; text-overflow: ellipsis; white-space: nowrap; }
.tester-result pre { max-height: 320px; margin: 0; padding: 16px; overflow: auto; color: #e2e8f0; background: var(--code-background, #101827); font-size: .75rem; line-height: 1.55; white-space: pre-wrap; overflow-wrap: anywhere; }
.http-status { padding: 3px 7px; border-radius: 6px; color: var(--success); background: var(--success-soft); font-size: .6875rem; font-weight: 750; }
.http-status--error { color: var(--destructive); background: var(--destructive-soft); }

@media (max-width: 800px) {
  .tester-grid { grid-template-columns: 1fr; }
}

@media (max-width: 560px) {
  .api-tester { padding: 12px; }
  .tester-heading { flex-direction: column; }
  .key-input-row, .dynamic-sender { grid-template-columns: 1fr; }
  .key-input-row :deep(.el-input__wrapper), .operation-card :deep(.el-input__wrapper), .operation-card :deep(.el-select__wrapper) { min-height: 44px; }
  .operation-actions { display: grid; grid-template-columns: 1fr 1fr; }
  .tester-result > header { align-items: flex-start; flex-direction: column; }
  .tester-result dl { width: 100%; display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }
}
</style>
